name: parana_despachante
description: App do Paraná Despachante
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  url_launcher: ^6.2.5
  dio: ^5.4.0
  permission_handler: ^11.3.0
  path_provider: ^2.1.2
  font_awesome_flutter: ^10.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/imagens/logo-parana-despachante-transparent.png
